// iCalendar generation. A malformed .ics fails silently in the subscriber's calendar app —
// no error, the events just never appear — so the format details get tested explicitly.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const win = {};
new Function("window", readFileSync(join(root, "assets/tools/ics.js"), "utf8"))(win);
const { build, escapeText, fold, addDays } = win.PDA_ICS;

const SAMPLE = {
  name: "Premier Dental Academy classes",
  description: "Class start dates",
  stamp: "20260812T000000Z",
  events: [
    { uid: "cohort-2026-08-17@premierdentalacademyoflongview.com", start: "2026-08-17",
      summary: "RDA class starts — In-person, Longview",
      description: "Daytime classes. Call (903) 913-6444 for current days & times.",
      location: "2800 Gilmer Rd, Suite 106, Longview, TX 75604",
      url: "https://www.premierdentalacademyoflongview.com/classes" },
  ],
};

test("produces a well-formed VCALENDAR", () => {
  const ics = build(SAMPLE);
  assert.match(ics, /^BEGIN:VCALENDAR\r\n/);
  assert.match(ics, /\r\nEND:VCALENDAR\r\n$/);
  assert.match(ics, /VERSION:2\.0/);
  assert.match(ics, /PRODID:/);
  assert.equal((ics.match(/BEGIN:VEVENT/g) || []).length, 1);
  assert.equal((ics.match(/END:VEVENT/g) || []).length, 1);
});

test("every line is CRLF terminated", () => {
  const ics = build(SAMPLE);
  const bareLf = ics.split("\r\n").join("").includes("\n");
  assert.equal(bareLf, false, "a bare LF breaks strict parsers");
});

test("all-day DTEND is exclusive, so a one-day event is not two days long", () => {
  const ics = build(SAMPLE);
  assert.match(ics, /DTSTART;VALUE=DATE:20260817/);
  assert.match(ics, /DTEND;VALUE=DATE:20260818/, "end date must be the following day");
});

test("addDays handles month and year boundaries", () => {
  assert.equal(addDays("2026-08-31", 1), "2026-09-01");
  assert.equal(addDays("2026-12-31", 1), "2027-01-01");
  assert.equal(addDays("2028-02-28", 1), "2028-02-29", "2028 is a leap year");
});

test("text values are escaped so separators cannot corrupt the file", () => {
  assert.equal(escapeText("a,b"), "a\\,b");
  assert.equal(escapeText("a;b"), "a\\;b");
  assert.equal(escapeText("a\\b"), "a\\\\b");
  assert.equal(escapeText("a\nb"), "a\\nb");
  const ics = build({
    ...SAMPLE,
    events: [{ uid: "x", start: "2026-08-17", summary: "Class; starts, today\nsecond line" }],
  });
  assert.match(ics, /SUMMARY:Class\\; starts\\, today\\nsecond line/);
});

test("long lines are folded at 75 octets with a leading space on continuations", () => {
  const long = "SUMMARY:" + "x".repeat(200);
  const folded = fold(long);
  for (const line of folded.split("\r\n")) {
    assert.ok(line.length <= 75, `line too long: ${line.length}`);
  }
  for (const line of folded.split("\r\n").slice(1)) {
    assert.equal(line[0], " ", "continuation lines must start with a space");
  }
  // Unfolding must give back exactly the original.
  assert.equal(folded.split("\r\n ").join(""), long);
});

test("an empty calendar is still valid rather than broken", () => {
  const ics = build({ name: "Empty", events: [] });
  assert.match(ics, /BEGIN:VCALENDAR/);
  assert.match(ics, /END:VCALENDAR/);
  assert.equal((ics.match(/BEGIN:VEVENT/g) || []).length, 0);
});

test("regenerating unchanged input produces an identical file", () => {
  // DTSTAMP is passed in rather than read from the clock, so a rebuild with no data change
  // does not produce a spurious diff on every run.
  assert.equal(build(SAMPLE), build(SAMPLE));
});

test("the generated calendar.ics on disk matches the cohort data", () => {
  const p = join(root, "calendar.ics");
  if (!existsSync(p)) return; // generated by npm run build:static
  const ics = readFileSync(p, "utf8");
  const cohorts = JSON.parse(readFileSync(join(root, "data/cohorts.json"), "utf8")).cohorts;
  const future = cohorts.filter((c) => c.status !== "cancelled");
  assert.equal((ics.match(/BEGIN:VEVENT/g) || []).length, future.length,
    "one event per non-cancelled cohort");
  assert.ok(!/night|evening|\dpm/i.test(ics),
    "the calendar must never publish evening class times — PDA does not offer them");
});
